apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rakkr-controller.fullname" . }}-api
  labels:
    {{- include "rakkr-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  {{- range $name, $value := .Values.api.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
