{{- if .Values.postgres.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rakkr-controller.postgresServiceName" . }}
  labels:
    {{- include "rakkr-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "rakkr-controller.postgresServiceName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "rakkr-controller.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "rakkr-controller.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rakkr-controller.postgresSecretName" . }}
                  key: {{ .Values.postgres.auth.passwordKey | quote }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.auth.username | quote }}
                - -d
                - {{ .Values.postgres.auth.database | quote }}
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      {{- if not .Values.postgres.persistence.enabled }}
      volumes:
        - name: postgres-data
          emptyDir: {}
      {{- end }}
  {{- if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          {{- toYaml .Values.postgres.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size | quote }}
        {{- if .Values.postgres.persistence.storageClassName }}
        storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}
        {{- end }}
  {{- end }}
{{- end }}
