{{- if and (eq .Values.secrets.backend "sealed") (not .Values.appSecret.existingSecret) -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "rakkr-controller.appSecretName" . }}
  labels:
    {{- include "rakkr-controller.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml (required "secrets.sealed.encryptedData is required for the sealed backend" .Values.secrets.sealed.encryptedData) | nindent 4 }}
  template:
    metadata:
      name: {{ include "rakkr-controller.appSecretName" . }}
      labels:
        {{- include "rakkr-controller.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
