{{- if .Values.appSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rakkr-controller.appSecretName" . }}
  labels:
    {{- include "rakkr-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.database.existingSecret.name }}
  DATABASE_URL: {{ include "rakkr-controller.databaseUrl" . | quote }}
  {{- end }}
  {{- range $name, $value := .Values.api.secretEnv }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
