#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RAKKR_LOOPBACK_REQUIRE_SND_ALOOP="${RAKKR_ALSA_JOB_REQUIRE_SND_ALOOP:-0}"
export RAKKR_LOOPBACK_PLAYBACK_MODE="${RAKKR_ALSA_JOB_PLAYBACK_MODE:-none}"
export RAKKR_LOOPBACK_CHECK_VOLUME="${RAKKR_ALSA_JOB_CHECK_VOLUME:-0}"
export RAKKR_LOOPBACK_WORK_DIR="${RAKKR_ALSA_JOB_WORK_DIR:-/tmp/rakkr-alsa-job-test}"
export RAKKR_LOOPBACK_NODE_ID="${RAKKR_ALSA_JOB_NODE_ID:-node_alsa_job_smoke}"
export RAKKR_LOOPBACK_RECORDING_ID="${RAKKR_ALSA_JOB_RECORDING_ID:-rec_alsa_full_agent}"
export RAKKR_LOOPBACK_JOB_ID="${RAKKR_ALSA_JOB_ID:-job_alsa_full_agent}"
export RAKKR_LOOPBACK_CAPTURE_DEVICE="${RAKKR_ALSA_JOB_DEVICE:-${RAKKR_ALSA_CAPTURE_DEVICE:-default}}"
export RAKKR_LOOPBACK_CAPTURE_FORMAT="${RAKKR_ALSA_JOB_FORMAT:-${RAKKR_ALSA_CAPTURE_FORMAT:-S16_LE}}"
export RAKKR_LOOPBACK_RATE="${RAKKR_ALSA_JOB_RATE:-${RAKKR_ALSA_CAPTURE_RATE:-48000}}"
export RAKKR_LOOPBACK_CHANNELS="${RAKKR_ALSA_JOB_CHANNELS:-${RAKKR_ALSA_CAPTURE_CHANNELS:-2}}"
export RAKKR_LOOPBACK_JOB_SECONDS="${RAKKR_ALSA_JOB_SECONDS:-${RAKKR_ALSA_CAPTURE_SECONDS:-5}}"
export RAKKR_LOOPBACK_EXPECT_CARD="${RAKKR_ALSA_JOB_EXPECT_CARD:-${RAKKR_ALSA_CAPTURE_EXPECT_CARD:-}}"
export RAKKR_LOOPBACK_CAPTURE_MIN_OUTPUT_BYTES="${RAKKR_ALSA_JOB_MIN_OUTPUT_BYTES:-${RAKKR_ALSA_CAPTURE_MIN_BYTES:-1024}}"
export RAKKR_LOOPBACK_JOB_SMOKE_LABEL="${RAKKR_ALSA_JOB_SMOKE_LABEL:-ALSA full-agent job smoke}"

exec bash "${script_dir}/agent-loopback-job-smoke.sh"
